### ISSUE TITLE
Authorization?

### ISSUE THREAD

**Issue by patie** [KSDaemon/wampy.js#10]
What about using authorization with wampy? wamp-cra or jwt, its possible? thanks

**Comment by KSDaemon** [comment]
hi @patie Thanks! :)
Yeah, right now there is no wamp-cra or any other auth support. But you can rely on http security, for example cookie, or some sort of session_id. Because websocket is a normal http request at first place, you can check that request at server side, and block connection to wamp router, if not authorized.

**Comment by KSDaemon** [comment]
Hi! From 3.0.0 version Wampy supports CRA! ;)
