### ISSUE TITLE
Do we need both argsDict and argsList? 

### ISSUE THREAD

**Issue by lucasrmendonca** [KSDaemon/wampy.js#196]
Maybe since both are Javascript Objects under the hood, we could add some logic to treat it as a single "args" variable instead of returning both?

**Comment by KSDaemon** [comment]
Well-well... That is a tricky question. Let me try to explain:

* argsList — may be omitted or it can be an array (empty or not)
* argsDict — may be omitted or it can be a hash-map (empty or not)

That is a part of the WAMP Protocol spec.

Now let's look at implementation. For example autobahn python and javascript versions pack the invocation handler results into `argsList[0]`, no matter what it is. And unpack it on the receiver side. So for example if Autobahn Callee returns a number 123 or array p [1,2,3] — it will be sent on the wire as [123] and [[1,2,3]], and unpacked on the autobahn receiver side back to 123 and [1,2,3]. But other clients, like wampy — will receive `argsList=[123]` and `argsList=[[1,2,3]]`. Not so good interop, right? You even can't describe your API to be the same independently of clients. 

Yeah, I suppose you are talking about a bit different thing: if we receive on the wire only argsList without argsDict and details — just return it instead of `{argsList, argsDict, details}`. Right?

But that is only for 1 case of all:

* no args, no kwargs, no details <<< Maybe this also
* args exists, no kwargs, no details <<< Only this one
* args exists, no kwargs, details exists
* args is empty, but due to protocol it can not be undefined/null, so it will be an empty array, kwargs exists
* args is empty, but due to protocol it can not be undefined/null, so it will be an empty array, kwargs doesn't exists, details exists

That's why I decided to always return the same result structure. Saving only one branch flow, but adding the need to check the result on the client side... IDK, what is the profit of it?....

**Comment by KSDaemon** [comment]
Maybe we can add a config option, kind of `simplifyResults` that will do what you propose...

**Comment by lucasrmendonca** [comment]
I was not aware of all the other use cases, I think it's better to keep it as it is then and let the client handle the results

**Comment by KSDaemon** [comment]
👍🏻
