### ISSUE TITLE
Wrong check of URI

### ISSUE THREAD

**Issue by bwegh** [KSDaemon/wampy.js#3]
Hi,
I am using your wampy.js for a simple router example with erwa.
Right now I am working on MetaEvents and am unable to subscribe to them due to the error

"error Topic URI doesn't meet requirements!" when subscribing to wamp.subscription.on_create

See:
http://crossbar.io/docs/Subscription-Meta-Events-and-Procedures/
http://crossbar.io/docs/Session-Metaevents-and-Procedures/

Thanks,
Bas

**Comment by KSDaemon** [comment]
Hi @bwegh! 
That's allright, because currently, Wampy doesn't suuport metaevents by itself. You are trying to get metaevents by subscribing as usual. But in this case, *wamp* is reserved word for URI, and can't be used as described in WAMP spec: 
Further, application URIs MUST NOT use wamp as a first URI component, since this is reserved for URIs predefined with the WAMP protocol itself.

You can simply patch wampy.js to allow wamp words:
```
diff --git a/src/wampy.js b/src/wampy.js
index 935e2ba..2347b6b 100644
--- a/src/wampy.js
+++ b/src/wampy.js
@@ -546,7 +546,7 @@
      */
     Wampy.prototype._validateURI = function (uri) {
         var re = /^([0-9a-zA-Z_]{2,}\.)*([0-9a-zA-Z_]{2,})$/;
-        if (!re.test(uri) || uri.indexOf('wamp') === 0) {
+        if (!re.test(uri)) {
             return false;
         } else {
             return true;
```

**Comment by bwegh** [comment]
thank you very much for your fast reply and help :+1: 
I will fork and patch.

I understand the spec in another way:
The application must not register or publish to uris starting with wamp, yet is allowed to subscribe or call such URIs (else the implementation in the router would not make much sense - IMHO).

In case you plan on chaning the behaviour, please let me know and I will reuse your original code.

**Comment by KSDaemon** [comment]
You are welcome!
Yep, i'm planning to implement metaevents in next releases.
