### ISSUE TITLE
Promise in register

### ISSUE THREAD

**Issue by darrrk** [KSDaemon/wampy.js#4]
Hello, @KSDaemon! Would be cool to consider returned promise in `register rpc` and send resolved value. [Autobahn inspiration](https://github.com/tavendo/AutobahnJS/blob/master/package/lib/session.js#L750).

**Comment by KSDaemon** [comment]
Hi, @darrrk! Yeah, i was thinking about that. But, there are some points we should take into account:
* Current API allows chaining (every method returns self wampy object). Returning promise will break that.
* Because wampy mean to be a production ready, we need to preserve backward compatibility.
* First thoughts about how promise can be implemented:
   * Additional config option, that change the behavior of public API methods (returning promises instead of self)
   * More API methods, for example with prefix “p” (for ex. call/pcall, register/pregister). That uses promises
   * Simply new separate version of wampy

Any thoughts?

**Comment by darrrk** [comment]
No, no! I mean another.
if I understand correctly, now rpc function must be synchronous and return value, that expected to response.
[register doc example](https://github.com/KSDaemon/wampy.js#registertopicuri-callbacks)
But js mostly asyncronous and I can return promise in rpc function, that resolved to simple value later.

**Comment by KSDaemon** [comment]
Nop, you are wrong. In register example, success function will be called asynchronously, after wampy will receive registration confirmation from WAMP router (via websocket connection). And rpc function also will be called asynchronously after receiving invocation from WAMP router.

**Comment by darrrk** [comment]
Yes, ok, I completely agree with you. Now let's consider the situation when calling rpc.
How I can inside rpc function make async action (for example, fetch data from db) and return result.

**Comment by KSDaemon** [comment]
Ough! Now i finally understand, what you mean! :)
Yes, thats not ok. I'll think how to do that! Thanks for pointing that out!
BTW, PRs are welcome! :)

**Comment by darrrk** [comment]
&#128522;

abstract code:
```javascript
Promise.resolve(
  rpcFunc(...)
).then(
  function(result){
    // result will proper if rpcFunc return Promise object or other value
  },
  function(){
    // error case
  }
)
```

But this not working in IE, old Android and nodejs 0.10.x 
But for this guys exist [es6-promise](https://github.com/jakearchibald/es6-promise)

**Comment by darrrk** [comment]
Relable it to enhancement
